version: '2'
services:
  rss-bridge:
    volumes:
      - ./whitelist.txt:/app/whitelist.txt
      - /app/caches
    build: ./bridges
    ports:
      - "3000:80"
    restart: unless-stopped
  server-service:
    build: ./app
    ports:
      - "8000:8000" # for development only
    volumes:
      - ./app/db:/usr/src/app/db # for development only
      - ./app/web:/usr/src/app/web # for development only