import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Test(ctx) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <p>{ctx[1]}</p>

      </main>
    </div>
  )
}

export async function getStaticProps(context) {
  // return fetch("http://django:8000/api/test").then((r) => {return await { props: {1: r.text()} }})
  const apiresp = await fetch("http://django-service:8000/api/test")
  
  return { props: {1: await apiresp.text()} }
}
